### ISSUE TITLE
Incompatible with WorldEdit 7 beta 2, 3

### ISSUE THREAD

**Issue by kaimokene** [taoneill/war#850]
Hello. I seem to have a issue when setting the zone. It says i havent set corner 2 when i have selected both corners of the arena with the worldedit wand.Using older version of worldedit since it creates a error with newer one (https://pastebin.com/zFfgmt1C) Using Paper 474 (MC 1.13.2) Tried WorldEdit 7.0.0 Beta 1 (for MC 1.13(.1) only) Gave no error but told me i havent set second corner, WorldEdit 7.0.0 Beta 2 (1.13+ ONLY!) Gave me the error above, Same with Beta 3 And latest dev build of worldedit.

**Comment by cmastudios** [comment]
Is this with War version 2.0.0-RC1?

**Comment by cmastudios** [comment]
In the meantime you can set zones the old way by clearing your worldedit selection and then running setzone as before.

**Comment by kaimokene** [comment]
Yes. It is War version 2.0.0-RC1 Its the 1.13 one from spigot i also tried the one on dev build site but made no difference it was also called 2.0.0-RC1. Okay ill try that way thanks

**Comment by kaimokene** [comment]
Pretty sure it was just me not making enough high selection with worldedit since i had basically same issue with built in one. Sorry about that. It was just confusing because it said corner 2 isnt selected. The error in console still remains though.

**Comment by cmastudios** [comment]
Log copied from above for posterity:
```[17:40:39 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'setzone' in plugin War v2.0.0-RC1
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.regions.Region.getMinimumPoint()Lcom/sk89q/worldedit/Vector;
        at com.tommytony.war.utility.Compat.getWorldEditSelection(Compat.java:58) ~[?:?]
        at com.tommytony.war.command.SetZoneCommand.handle(SetZoneCommand.java:29) ~[?:?]
        at com.tommytony.war.command.WarCommandHandler.handle(WarCommandHandler.java:141) ~[?:?]
        at com.tommytony.war.War.onCommand(War.java:318) ~[?:?]
```
I'll work on the WorldEdit 7.0.0 beta 2 and 3 incompatibility issues.

**Comment by cmastudios** [comment]
Fixed: try [War v2.0.0-RC2](https://maven.cmastudios.me/com/tommytony/war/2.0.0-RC2/war-2.0.0-RC2.jar).

**Comment by kaimokene** [comment]
Yep this fixed it thanks.
